player-info-forwarding-mode = "modern"
announce-forge = true
forced-hosts = {}

#If you are using modern or BungeeGuard IP forwarding, configure a file that contains a unique secret here.
#The file is expected to be UTF-8 encoded and not empty.
forwarding-secret-file = "forwarding.secret"
config-version = "2.7"

#Should the proxy enforce the new public key security standard? By default, this is on.
force-key-authentication = true
# What should be the MOTD? This gets displayed when the player adds your server to
# their server list. Only MiniMessage format is accepted.
motd = "Babies R Us"

[servers]
        vanilla = "192.168.10.69:25567"
        survival = "192.168.10.69:25566"
        creative = "192.168.10.69:25568"
        try = ["vanilla", "survival"]
[advanced]
        #Allows players transferred from other hosts via the
        #Transfer packet (Minecraft 1.20.5) to be received.
        accepts-transfers = false